on: pull_request_review
name: Team awesome's approval workflow
jobs:
  labelWhenApproved:
    name: Team awesome's approval workflow
    runs-on: ubuntu-latest
    steps:
    - name: Team awesome's approval workflow
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "2"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
        REMOVE_LABEL: "awaiting%20review"
